# Name of your workflow
name: Docker Build and Push

# This tells GitHub WHEN to run
on:
  # Run on every push to the "main" branch
  push:
    branches: [ "main" ]
  # Also allows you to run it manually from the Actions tab
  workflow_dispatch:

# This tells GitHub WHAT to do
jobs:
  build_and_push:
    # Give the job a name
    name: Build and Push to Docker Hub
    # Tell it to run on the latest version of Ubuntu
    runs-on: ubuntu-latest

    # These are the actual steps to run
    steps:
      # Step 1: Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub
      # This step uses the secrets you just created
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Build and tag the Docker image
      - name: Build and push the Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          # This names the image 'thegrimdev/my-flask-app:latest'
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-flask-app:latest
          # This tells the action to push (upload) after building
          push: true
